### ISSUE TITLE
Проверка взаимодействия

### ISSUE THREAD

**Issue by pi-null-mezon** [Pastor/videotools#1]
Андрей привет, я залил первое своё обновление. Хочу чтобы ты посмотрел его на предмет пригодности для разрабатываемого проекта. Все вопросы в комментариях.

**Comment by Pastor** [comment]
Извини, не увидел сразу бранч. Все оке, посмотрел. Выглядит хорошо, но я бы кое что подправил :)

Лицо уже находится и выдается по нему данные, поэтому классификаторы излишни, единственно не ищутся глаза. Могу добавить в основное определение, чтобы тебе не парится

**Comment by pi-null-mezon** [comment]
Да это я виноват, что про ветку не написал, прости пожалуйста. В каком модуле лицо ищется? Я бы мог в plugin эти алгоритмы переписать, по крайней мере до твоего сообщения собирался это сделать.

**Comment by Pastor** [comment]
Давай я немного попозже тебе все пришлю, я пока на лекции. Освобожусь и напишу как и где

**Comment by pi-null-mezon** [comment]
А ты где лекции читаешь? По какой дисциплине?

**Comment by Pastor** [comment]
ООП Java - Кафедра ИИС - МИРЭА
ООП C++  - Кафедра ИТС - МИРЭА

**Comment by pi-null-mezon** [comment]
Залил очередное обновление в ветку evaluations. Моя часть готова к тестированию (контраст+резкость+отношение_сигнал_шум). Андрей посмотри пожалуйста мой код, что бы ты поправил в нём? Мне очень интересно. Будет здорово, если ты внесёшь свои правки, а я потом сам в сравнении их посмотрю.

**Comment by pi-null-mezon** [comment]
Ещё вот что, все три функции оценки качества работают независимо друг от друга, поэтому их можно исполнять параллельно в трёх потоках и выиграть по времени в три раза. Ну это на всякий случай, если производительности не будет хватать для обработки в режиме реального времени.

**Comment by Pastor** [comment]
Я тогда сливаю ветки в основную и немного подправлю. А так все написано хорошо. По поводу распаралеливания - идея хорошая, можно попробовать, но немного позже :)
