### ISSUE TITLE
Поиск глаз

### ISSUE THREAD

**Issue by Pastor** [Pastor/videotools#3]
Немного подправлен код и готов к использованию. Только пока не сделано автоматическое  копирование файлов `haarcascade_mcs_lefteye.xml` и `haarcascade_mcs_righteye.xml` в директорию сборки - это сделаю потом. Сейчас эти файлы можно вручную скопировать их директории `3rdparty/stasm`.

**Comment by pi-null-mezon** [comment]
Ок, я добавил расчётную часть. Собирать не пробовал.

**Comment by Pastor** [comment]
Немного переделал, до работающего состояния. Теперь все находит

**Comment by pi-null-mezon** [comment]
Ну что, тогда всё, задача выполнена.
